#BYLAWS OF GLENLAKE UPSTATE HOMEOWNERS ASSOCIATION, INC.

## Binding Arbitration
This is the First page of the Bylaws of Glenlake Upstate Homeowners Association, Inc.
Pursuant to South Carolina Code Section 15-48-1 O et seq; 1976, as amended, these
Bylaws are subject to the following:

THESE BYLAWS ARE SUBJECT TO ARBITRATION UNDER ARTICLE VI HEREIN. THESE BYLAWS ARE BINDING ON ALL MEMBERS OF THE ASSOCIATION,
INCLUDING ANY PERSON OBTAINING FINANCIAL RIGHTS IN THE HOMEOWNERS ASSOCIATION.

In the event other pages, including, but not limited to, cover pages, indexes, or tables of contents. are placed in front of this page, those pages shall not be deemed the first page. This page and only this page shall be deemed or considered the first page of the Bylaws for all legal purposes. 

#BYLAWS OF GLENLAKE UPSTATE HOME.OWNERS ASSOCIATIONt INC. 

#ARTICLE I NAME MEMBERSHIP, APPLICABILITY AND DEFINITIONS 

## 1.1 Name. 
The name of the corporation shall be Clenlake Upstate Homeowners Association, Inc. ("Association"). 

## 1.2. Membership. 
The Association shall have two (2) classes of membership, as is more fully set forth in that certain Declaration of Protective Covenants, Conditions and Restrictions for Glcnlakc Subdivision ("Declaration"), the terms of those of which pertain to membership are specifically incorporated by reference herein. 

## 1.3. Definitions. 
The capitalized words used in these Bylaws shall have the same meaning as set forth in the Declaration, unless the context shall correspond otherwise. 

# ARTICLE II ASSOCIATION: MEETINGS, QUORUM, VOTING, PROXIES 

## 2.1. Place of Meetings. 
Meetings of the Association shall be held at the Association's principal office or at such other suitable place convenient to the members as may be designated by the Board, either in the Community or as convenie nt to the Community as possible and practical. 

## 2.2. First Meeting and Annual Meetings. 
An annual or special meeting shall be held within o ne year from the date the Declaration is re corded. Annual meetings shall be set by the Board so as to occur no later than sixty (60) days after the close of the Association's fiscal year. 

## 2.3. S p ecial Meetings. 
The President may call special meetings. In addition, it sh all be the President's duty to call a special meeting of the Association if so directed by resolution of the Board or upon a petition si g n ed by at least five (5%) percent of the Total Association Yule (the consent of the Declarant sh all not be required). The notice of any special meeting shall state the d ate, time, and place of such meeting and the purpose thereof. No business shall be transacted at a special m eeting, e xcept as stated in the n otice. 

##2. 4. Notice of Meetings. 
It shall be rhe duty of the S e cretary to mail or to cause to be delivered to the Owner of each Lot (as sh own in the rec ords of the Ass o ciati on) and to the Declarant, so long as Declarant owns any real properly within the Community, a notice of each annual or speci al meeti ng of the Associ ation stating the time and place w h ere it is to be held a nd in the notice of a special meeting, the p urpose there o f. If an Owner wish es notice to be given at an address other than his or her Lot, the Owner shall designate such other address in writing to the Secretary. The mailing or delivery of a notice of meeting in the manner provided in this Section shall be considered service of notice. Notices shall be served not less than ten (l 0) nor more than sixty (60) days before a meeting. 

## 2.5. Waiver of Notice. 
Waiver of notice of a meeting of the members shall be deemed the equivalent of proper notice. Any member may, in writing, waive notice of any meeting of the members, eit her be fore or after such meeting. Such written notice shall be d elivered to the Secretary for in clusion in the Ass o ciation's minutes. Attendance at a m e eting by a m ember, whether in pers on or by proxy, shall be deemed waiver by such me mber of notice of the time, date, and place thereof, unless such me mber speci fically o bjects to lack of pro per notice at the time the meeting is c alled to order. 

## 2.6. Adjournment of Meetings. 
If any meeti ngs of the Association cannot be held because a quorum is not pres e nt, a majority of the members who are pr esent at such m eeting, either in person or by proxy, may adjo urn the meeting to a ti me not less than five (S) nor more than thirty (3 0) days from the time the original meeting w as called. At su ch adjourned meeting at which a quorum is present, any business which might have been trans acted at the meeting originally called may be transa cted without further notice. 

## 2.7. Voting. The voting ri g hts of the members shall be as set forth in the Articles of Incorporation and the Declaration, a nd such voti ng ri ghts are specifically inco rp orated by this reference. 

## 2.8. Proxies. 
At all meetin gs of members, each memb er may v ote in person or by pro xy. All proxies shall be in writing, dated, and filed with the Secretary before the ap pointed time of each m eeti n g. E very proxy shall be re v oca ble and sh all auto m atically cease u p on conveyance by the m e mber of such member's Lot, or u p on recei pt of n o ti ce by the Secretary of the death or ju dici ally declar ed incompete nce of a member> or of wri tten revoc ation, or upon the expir ation of eleven ( 1 1 ) mont hs from the date of the proxy. 

## 2.9. Quorum. 
The presence, in person or by proxy, of twe nty-five (25%) perc e nt of the total eli gible Association vote sh all constitute a qu orum at all meetin gs of the Association. T he members present at a d uly c alled or h eld meeting at which a q u orum is present m ay contin ue to do busin ess until adjo urnment, notwithstanding the wit hdra wal of en ough members to leave less than a q u orum. Any amendment to this Section sh all com ply with the provisio ns of the South Carolina Nonprofit Corporation Act, S.C. Code Section 33-31- I 0) et seq. 

## 2.10. Action With out A Furmal Meeting. 
A ny action to be tak en at a meeting of the members, or whi ch m ay be ta ken at a meeting of the members, may be ta ken with out a m e eti ng if o ne or m ore written consents setting forth the action so taken sh all be signed by members holding at least eighty (8 0%) p erce nt of the Ass ociation's voti ng power. Action tak en with out a me eting shall be eff ective on the d ate th at the last conse nt is e x ecuted, and co nsented to by the Declarant (so long as Declarant o wns any pro perty within the Com m u nity) unless a later effective date is specified ther ein. E ach signed conse nt shall be delivered to the Associati on and sh all be incl uded in the mi n utes of m eetin gs of members filed in the permanent rec ords of the Ass ociation. Written notice of member approval pursuant lo this Section must be given to all members who have not signed the written consent. Provided, however) that so long as Declarant holds a majority of the voting power of the Association, Declarant may take action without a meeting, in its sole discretion. 

## 2.11. Action By Wrirten Ballot. 
Any action to be taken at any annual, regular, or special meeting of members may be taken without a meeting if approved by written ballot as pr o vided herein. The Ass ociation shall d eliver a writt en ballot to ea ch member entitled to vote on the matter. The written ballot shall set forth each pro p osed action and provi de an opportunity to vote for or a gainst e ach pro pos ed action. Approval by written ballot of an a ction shall be valid only w h en the number of votes cast by ballot equals or exceeds the q uorum re q uired to be present at a meeting held to a uthorize such action and the n u m ber of ap provals equals or exceeds the n umber of votes that w o uld be required lo approve the ma tter at a meeting at which the total num ber of v otes cast was the same as the number of v otes c ast by ballot. AIJ solicitatio ns for votes by written ballot shall indic ate the n u m b er of responses needed lo meet the quorum requirements; state the percentage of approvals necessary to approve each matter other than election of dir ectors; and specify the time by which a ballot m ust be received by the Asso ciation in or der to be co unte d. A timely written ball ot receiv ed by the Ass ociation may not be revoked without the consent of the Board. The results of each action by written ballot shall be certifi ed by the Secretary and sh all be included in the min utes of meetings of memb ers filed in the Ass o ciation's perm ane nt records. 

# ARTICLE III BOARD OF DIRRCTORS: NUMBER, POWERS, MEETINGS 

# A. Comp osition and Selectio n. 

## 3.1. Governing Body; 
Composition. T he affairs of the Association shall be g o verned by a B oard of Directors. Exce pt as pro vided in Section 3 .2, the directors m ust reside in the Commu nity and shall be members or sp ous es of such members; however, no person and his or her sp ouse may serve on the B o ard at the same lime. 

## 3.2. Directors Appointed by Declarant. 
The Declarant shall have the right to appoi nt or rem ove any m e m b er or members of the Board or any o fficer or o fficers of the Association until such time as the first of the f ollowi ng eve nts shall occur: (a) Decem b er 31, 2012; (b) when the tot al vot es outstanding in the Class A m e m bership exceed the total vo tes outstanding in the Class B mem bership; or (c) the surrender by Declarant in writing of the a uthority to ap p oint and remove directors and officers of the Association. Each Owner, by acceptance of a deed to or other co nveyance of a Lot, vests in Declarant such a uthority to appoi nt a nd rem ove dire ctors and o fficers of the A sso ciatio n. T he directors selected by the Declarant need not be Owners or residents in the Com m unity. 

## 3.3. Number of Direct o rs. 
The B o ard shall consist of three m e m bers. A fter the Declarant's ri g ht to a ppoint directors and officers terminates, the B o ard may exp a nd the nu m b er of directors to five or seven members, which sh all be filled by a vote of the me mbers in a c corda nce with Secti on 3.S( b).

## 3.4. Nomination of Directors. 
Elected directors shall be nominated from the floor and may also be nominated by a nominating committee, if such a committee is established by the Board. All candidates shall have a reasonable opportunity to communicate their qualifications to the members and to solicit votes. 

## 3.5. Election and Term of Office. 
Owner-elected directors shall be elected and hold office as follows: (a) After the Declarant's right to appoint directors and officers terminates, the Association shall call a special meeting to be held at which Owners shall elect three directors. (b) Thereafter, directors shall be elected at the Ass ociation's annual meeting. All eligible members of the Ass o ciation shall vote on all direct ors to be elected, and the candidate(s) receiving the most v otes shall be elected. At the special meeting in which the Owners initially el ect directors, two directors shall be elected to tw o-year ter ms and o ne director shall be elected to a one-y ear term. At the ex piration of the initial term of offi ce of e a ch respective Owner-elected dire ctor, a success or shall be elected to serve for a term of t\'VO years. T he directors shall h old o ffice until their respective su ccessors shall have been elected by the Association. 

## 3.6. Removal of Directors. 
At any regular or special meeting of the Association duly c alled, any one or more of the directors may be re moved, with or with o ut cause, by a majority of the Total Association Vote and a succ essor may then and there be elected to ft) I the v acan cy th us create d. A dire ctor whose removal has been proposed by the Ow ners sh all be given at le ast ten ( I 0) d ays' notice of the calli ng of the meeting and the purpose thereof and sh all be given an opp o rtunity to be heard at the meeting. A dditio nally, any director who h as three (3) consec utive un e xcused abse n ces from B o ard meetings or who is delinquent in the p a y ment of an assessm ent for m ore than 30 d ays may be removed by a m ajority vote of the remaining direct ors at a m eeting. T his Section sh all not apply to directors ap p ointed by Declarant. 

## 3.7. Vacancies. 
Vacancies in the B o ard caused by any reaso n, e xcludi ng the remov al ofa dir e ctor by v ote of the A ss o ciation, shall he filled by a vote of the majority of the remaining directors, even th o ugh less than a qu o ru m, at a ny m eeting of the B oard. Ea ch person so selected shall se rve the u n e x pired p o rtion of the term. 

# B. Meetings. 

## 3.8 Organizational Meetings. 
The first meeting of the Board foll o wing each annu al membership meeting shall be held within ten (10) days thereafter al such Lime and place as sh all be fixed by the Board. 

#3.9. R egular Meeti ngs. 
Regular meeti ngs of the B oard may be held at su ch ti me and place as shall be deter mined from ti me to time by a m ajority of the directors. but at least four (4) such meetin gs shall be h eld d uring e ach fis cal year with al le ast one per q u a rter. Notice of the re g ular sch edule shall co nstit ute suffi cie nt notice: of such meetings. So long as the Declarant h as the right to appoint directors to the Board, Declarant shall have the option 10 hold only one (1) meeting per fiscal year. 

## 3.10. Special Meetings. 
Special meetings of the Board shall be held when requested by the President, Vice President, or by any two directors. The notice shall specify the time and place of the meeting and the nature of any special business to be considered. The notice shall be given to each director by one of the following methods: (a) by personal delivery; (b) written notice by first class mail, p ostage prepaid; (c) by teleph o ne communication, either directly to the director or to a person at the director's ho me or office who w ould reasonably be exp e cted to communicate such n otice promptly to the director; (d) ele ctronic messag e, fiber optic, or telecommunication to the director; or (e) by comm e rcial delivery service to su ch director's home or office. All such n oti ces shall be giv en or se nt to the director's a ddress. telephone nu mber, or other pl a ce of deliv ery as shown on the Association's records. Noti ces sent by first class mail sh all be de p osited into a United States mailbox at least four (4) days before the ti me set for the meetin g. Notices given by personal delivery, telephone, or telecommunication shall be given at least forty-ei g ht (48) hours before the ti me set for the meeting. 

## 3.11. Waiver of N otice. 
T he tr ansa ctions of a ny B oard meeting, however called and noticed or w h ere v er h eld, shall be as valid as tho u gh taken at a meeti ng duly held a ft er regular call and n otice, if (a) a qu orum is present, and (b) either be f ore or after the meeti ng, each of the directors not present si g ns a written waiver of n otice, a consent to holding the meeting, or an a p pro v al of the mi n utes. The waiver of notice or consent need not specify the purp ose of the meeting. Noti ce of a m eeting shall also be deemed given to any director w ho attends the m eeting with out protesting before or at its c omme ncement about the lack of ade quate notice. 

## 3.12. Quorum of Board of Directors. 
At all Board meeti n gs, a m ajority of the directors shall co nstitute a quor um for the transacti on of b usiness. and the v otes of a m ajority of the directors present at a meeti ng al which a q uorum is pr ese nt shall constitute the decision of the Bo ar d. A meeting at whi ch a qu orum of dir ectors is present initially may co ntinue to tr ansa ct business, not withstanding the withdr awal of dire ctors, if at least a m ajority of the required q u orum for that meeting appro v es a ny action ta ken. If the B o ard ca n not hold a meeting b eca use a q u o rum is not present, a majority of the dir ectors at such meeting may a djourn the m eeting to a ti me not less than five (5) or more than thirty (30) d a ys from the date of the ori ginal meetin g. At the recon v ened meetin g, if a qu orum is pr esent the B o ard may transact, with o ut further notice, a ny business which it might h a ve transacted al the origi nal meeting. A ny amend ments to this S e c ti on shall comply with the pr o visions of the S o uth C arolina N onpr o fit C o rp oration Act, S.C. Code Section 33-31-10, et seq. 

## 3.13. Compensati on. 
No dir ector shall receive any compensation from the Association for acti ng in such ca pacity. 

## 3.14. Open Meetings. 
All meetin gs of the Board shall be o pen to all members, but members oth er than directors may not p articipate in a ny discussion or delib eration, unless e x pressly so auth orized by the B oard.

## 3.15. Executive Session. 
T he Board may adjo urn a meeti ng and recon v e ne in e x ecutive session to disc uss and vote u p on perso nnel matt ers, I itigation in which the Association is or may become involved, and orders of business of a similar nature. The nature of any and all business to be considered in executive session shall first be announced in open session. 

## 3.16. Action Without A Formal Meeting. 
Any action to be taken at a meeting of the directors or any action that may be taken at a meeting of the directors may be taken without a meeting if one or more consents, in writing, setting forth the action so taken, shall be signed by a majority of the directors and delivered to the Association for inclusion in the minutes for fili ng in the co rporate records. 

## 3.17. Telephonic Participation. 
One or m ore directors may partici pate in and v ote duri ng any re g ular or special B o ard meeting by telephone confere nce call or similar c ommunication equipment by means of which all persons partici pating in the meeting can hear each other at the same time, and th ose d irect ors so participating shall be present at su ch meeting. Any such meeting at w hich a qu orum p a rticipates sh al\ constitute a meeting of the B oard. 

# C. Powers and Duties. 

## 3.18. Powers. 
The Board shall be resp onsible for the affairs of the Association and shall have all of the p o wers and duties ne cessary for the ad ministration of the Associati o n's affairs and, as pro vided by law, m ay do all acts a nd things as are not by the D eclaration, Arti cles, or th ese Bylaws directed to be done and ex ercised exclusively by the mem b ers. In ad dition lo the duties imposed by these Bylaws or by a ny resoluti on of the Association that may herea fter be adopt ed, the Board shall have the power to and be res ponsible for the f ollowing, in way of explanation, but n ot li mitation: (a) pre paration and ad o ption of an annual budget in which there shall be established the contribution of each O w ner to the common ex penses; (b) making ass essments lo d efr ay the common ex penses and esta blishing the me ans and methods of collecting such assessments; (e) providi ng for the o peration, care, u p kee p, and maintenance ofall areas w hich are the maintenance responsibility of the Association; (d) designating, hiring, and dismissing the personnel ne cessary for the o peration of the Asso ciation an d, where ap propriate, providing for the compensation of such p erso nn el and for the purchase of equipment, supplies, and material to be used by such personnel in the perf o rmance of th eir duties; (e) collecti ng the assessm ents, depositing the proceeds thereof in a bank depository whi ch it sh all approve> a nd using the pro cee ds to administer the Association; (f) m a king a nd a m ending use restrictions and mies and regulations; (g) o pening of bank accounts on behalf of the Association and d esignating the si g n atories re q uired; (h) enforcing by legal means the provisions of the Declaration, these By Laws, and the rules and regulations adopted by it, and bringing any proceedings which may be instituted on behalf of or against the Owners concerning the Association; obtaining and carrying insurance against casualties and liabilities, as provided in the Declaration, and paying the premium cost thereof; G) paying the cost of all services rendered to the Association or its members which are not directly chargeable to Owners; (k) keeping books with detailed accounts of the receipts and expenditures affecti ng the Association and its administration, a nd specifying the m aintenance and repair expenses and any other e x p e nses inc urred; and functions. (I) contracting with any Person for the performa nce of various d uties and 

## 3.19. Managem ent Agent. 
The B oard may employ for the Ass o ciation a pr o fessional management agent or agents at a compensation est a blished by the Board to perform such duties and servic es as the Board shall authori z e. The Declar a nt or an affiliate of the Declarant m ay be employed as man a ging a gent. The term of any mana g e m ent agreement shall n ot e xceed o ne ( 1) year and sh all be subject to termination by either party, without cause and with out pe n alty, upon not m ore than ninety (90) days' written n otice. 

## 3.20. Borrowing. 
The Board sh all have the p o wer to bo rrow money without the approval of the members of the Association provided that the Board shall obtain membership ap pro val in the same m anner as for special assess m ents, so lo ng as the pro posed borro wing is for the purp ose of modifying, im proving, or adding amenities, a nd the total amount of such borrowing d oes not exceed ten th ousand ($10,000.00) dollars of o utstan ding de bt at any o ne time. 

## 3.21. Fi ning or Suspension Procedure. 
T he B o ard shall not im p ose a fine (a late charge shall not constitute a fine) or suspend a members right to use any part of the Common Properly u nless and u ntil the following proce d ure is f ollowed: (a) Notice. Written notice shall be served u pon the violator by first-cl ass or certified mail sent to the last address of the m e m b er sho wn on the Association's rec ords, speci f ying: (I) the nature of the vi olation, the fi ne or sus pension to be imposed, and the date, not less than fifteen (15) days from the date of the noti ce, that the fine or suspension will take effect; (2) that the vi olator m a y. within ten ( I 0) da ys from the date of the notic e, request a h earing regarding the fine or suspension im posed; (3) the nam e, address, and tele pho ne nu m bers of a person to c ontact to challen ge the fine or susp e nsion; ( 4) that any state m ents, evidence, and wit n esses may be produ ced by the violator at the hea ring; a nd (5) that all rights to have the line or suspension reconsidered are waived if a hearing is not requested within ten ( I 0) days of the date of the notice. [b) Hearing. If a hearing is requested, it shall be held before the Board in executive session, and the violator shall be given a reasonable opportunity to be heard. The minutes of the meeting shall contain a written statement of the results of the hearing. No fine or suspension shall be imposed prior to the date that is five (5) days after the date of the hearing. (c) Enforcement. 1n any action or proceeding to enforce the D eclaration, th ese Bylaws, the rules and reg ulatio ns of the Associ ation, or decision of the B oard, the Association shall be entitled to recover all expenses from the violator, in cluding all attorney's fees. 

# ARTICLE IV OFFICERS 

## 4.1. Offic ers.
The officers of the Ass o ciation shall be a President, Secretary, and Treasurer. Any two or m ore offic es m ay be held by the same person, excepting the of fices of President and Secretary, The President a nd Treasurer shall be el e cted from among the m e mbers of the Board. The Board may app oint such other offic ers, including one or m ore Vice Presid ents, Assistant Secretaries, or Assistant Treasurers, as it shall deem desirable. 

## 4.2. Ele ctio n, T e rm of Office, a nd Va cancies. 
Exc e pt d uring the peri od in whi ch the Declarant has the right to app oint the o ffi cers of the Association under Section 3 .2, the officers of the Association shall be elected an nually by the B o ard at the first me eting of the B oard f ollowi ng ea ch annual meeting of the me mbers. A v acancy in any o ffi ce arising because of death, resi g natio n, rem oval, or otherwise may be filled by the B o ard for the unex pir ed p ortion of the te rm. 

## 4.3. Removal. Any o ffi cer may be removed by the B o ard whe never, in its ju dgm ent, the b est inter ests of the Association will be serv ed thereby. 

## 4. 4. President. 
The Preside nt shall be the c hief ex ecutive officer of the Ass ociation and shall preside at all Asso ciation a nd B o ard meetings, The President shall h ave all the g e neral p o wers and duties w hi ch are in cid e nt to the o ffi ce of the president of a co rpor ation organiz ed under the: South C aroli na N o n pro fit Cor p oration Act. 4.5. Vice President. If appoi nted by the B o ard, the Vice Presid e nt sh all a ct in the Presi d e nt's abs ence and sh all h ave all po wers, d uties, and responsi bilities provided for the Pr esid e nt when so a ctin g. 4.6. Secretary. The Secretary shall keep the min utes of all m eetin gs of the Ass o ciation and of the B oard a nd shall have c h arge of su ch b o o ks and papers as the Board m ay direct and shall, in gen eral, perf orm all d uties incid e nt to the office of the secret ary of a co rporati on organized in accordance with South Carolina law. 

## 4. 7. Trcasu rer,
The Treasurer shall have the responsibility for the Association's funds and securities and shall be responsible for keeping full and accurate financial records and books of account showing all receipts and disbursements, for preparing all required financial statements and tax returns, and for the deposit of all monies and other valuable effects in the name of the Associ ation or the ma naging agent in such depositories as may be designated by the B o ard from time to time. 

## 4.8. Resignation. 
Any officer may resign at any ti me by giving written notice to the Board. Such resignati on shall take effect on the d ate of the receipt of such n otice or at any later time spe cified therein, and unless otherwise sp ecified therein, the accepta nce of su ch resignation shall not be necessary to make it e ffectiv e. 

# AR TICLEV COMMITTEES

Committe es to perform such tasks and to serve for such p erio ds as may be designated by the Board are hereby authorized. Each co mmittee shall be comp osed and sh all oper ate in accorda nce with the terms of the resolution of the B oard designating the c o m mitt ee or with rules ad o pted by the B o ar d. 

# A R TICLE VI MISCELLANEOUS

## 6.1. Fiscal Y ear.
The fiscal year of the Association shall be the cale ndar y ear, unless ot h erwise determined by resoluti on of the B o ar d. 

## 6.2. Parliame ntary Rules. 
Roberts Rules of Ord er (c u rr e nt editio n) sh all g overn the conduct of all Associati on procee din gs, wh en n ot in conflict with S o uth Carolina law, the Articles of Inco rp oration, the D ecl aration, these Bylaws, or a ruli ng made by the pers on presiding o ver the pr oceedin g. 

## 6.3. Conflicts, 
If there are con flicts or inconsistencies between the provisio ns of S o uth Carolina law, the Articles of Incorporation, the Declaration, and these Bylaws, the provisions of South Caroli na law, the Declarati o n, the Articles of Incor poratio n, and the Byla ws (in th at order) sh all prevail. 

## 6.4. Amendment.
These Bylaws m ay be amended by the Board if such amend ment is necessary: (a) to bri ng any pro vision hereof into c ompli an ce with a ny applica ble g o vernm ental statur e. rule, re gul ati on, or judicial determination; (b) to enable any title insurance c ompany to issue title insurance cov era ge with respect to the L ots subject to the Declaration; (c) to meet the requireme nts of an institutional or governmental le n der or p urchaser of mortgage loans, incl uding. for example> the F e d eral N atio nal M o rtga ge A ss ociation or Fed eral H o me L oan Mortg a ge Corporation, to enable such lender or purchaser to make or purchase Mortgage loans on the Lots subject to the Declaration; or ( d) to enable any governmental agency or private insurance company to insure or guarantee Mortgage loans on the Lots subject to the Declaration Further, so long as Declarant has the right unilaterally to subject additional property to the Declaration, Declarant may unilaterally amend these Bylaws for any other purpose; however, such amendm e nt shall not ad versely affect the substantive rights or title of any Lot Owner without the consent of the affected Lot Ow ner. In addition, these Bylaws may be ame nded upon the affirmative vote or written consent, or any combi nation thereof, of at least tw o-thirds (2/3) oflhe Total Association Vot e, and the c onsent of Declarant, so long as Declarant o w ns a ny property within the C ommunity. T he U.S. Departm e nt of Veterans Affairs (if it is then guara nte eing M ortgages in the Com m u nity or h as issued a project approval for the guara nteeing of such mortgages) and/or the U.S. D epartm e nt of H ousing and Urban Develo pment (if it is th en ins uring any M o rtg a ge in the Community or has issu ed a project approv al for the insuring of such m ortg a ges) sh all have the right to veto amendments to these B ylaws for as long as the Declarant has the ri g ht to appoinl and remove the directors and offi c ers of the Associatio n.

## 6.5. Al'biiration. 
A LL MEMBERS OF THE ASSO CIATION AGREE THAT ANY OlSP UTE ARISING BY AND BETWEEN THE MEMBER S, ANY DI SPUTE ARISING BETWEEN THE MEMBERS AND THE ASSOCIATION. W H E THER DERIVATIVE OR OTHERWISE, OR ANY DlSPUTE ARISING BETWEEN THE ASS OCIA TION AND THE DEVELOPER. "POINSETT DEVELOPMENT. LLC", SH ALL BE RESOLVED THR OUGH ARBITRATION PURSUANT TO THE RU LES PRO MULGATED BY THE A MERICAN ARBJTRA TION ASSO CIA TION. THE PARTIES A



FIRST AMENDMENT TO BYLAWS OF GLENLAKE UPSTATE HOMEOWNERS ASSOCIATION, INC. THIS FIRST AMENDMENT TO BYLAWS OF GLENLAKE UPSTATE HOMEOWNERS ASSOCIATION, INC. is made as of this 7th day of March, 2006. 1. 

# ARTICLE Ill - BOARD OF DIRECTORS: NUMBER, POWERS, MEETINGS: 
## Paragraph 3.3 (Number of Directors)
is revised by changing the second sentence to read as follows: After the Declarant's right to appoint directors and officers terminates, the Board shall expand the number of directors to five or seven members, which shall be filled by a vote of the members in accordance with Section 3.5(b). Paragraph 3.5 (Election and Term of Office): a. Subparagraph (a) is changed so that five (5) directors shall be elected rather than three. b. The first sentence of the second paragraph of Subparagraph (b) is hereby deleted and replaced with the .following sentence. Changes are noted in italics: At the special meeting in which the Owners initially elect directors, three directors shall be elected to two-year terms and two directors shall be elected to one-year terms. c. The following provision is hereby added: (c) At all times after the expiration of Declarant's right to appoint directors and officers, at least one member of the Board of Directors shall be an Owner-occupant of a Lot on which a townhome is constructed. Any such director(s) shall also sit on the Townhome Committee, as described elsewhere in the Bylaws and the Declaration. 

# 2. ARTICLE V-COMMITTEES: 
The Article is hereby amended by making the existing language Paragraph 5.1 and by adding Paragraph 5.2 as noted below:


# 5.1 General Committees.
Committees to perform such tasks and to serve for such periods as may be designated by the Board are hereby authorized. Each committee shall be composed and shall operate in accordance with the terms of the resolution of the Board designating the committee or with rules adopted by the Board. 

## 5.2 Town home Committee. 
Immediately prior to the termination of the Declarant's right to appoint directors and officers, there shall be created by the Board a "Townhome Committee." The Townhome Committee shall have five (5) members, all of whom shall be Owners and occupiers of town home Lots. Three (3) of the initial Committee Members shall serve two (2) year terms and two (2) of the initial Committee Members shall serve one (1) year terms. Thereafter, the Members of the Townhome Committee shall be nominated and elected exclusively by those Members of the Association who are Owners of townhome Lots and those Members so elected shall serve one (1) year terms. Upon proper vote, Members of the Townhome Committee may be re-elected for additional terms. The Board of Directors shall delegate to the Townhome Committee the following rights and duties: 1. With respect to those matters which pertain exclusively to the management and maintenance of the townhomes in the Community, any and all rights of the Board provided by the Bylaws, the Declaration or by law, including, but not limited to, a. The preparation and adoption of an annual budget in which there shall be established the contribution of each townhome Lot Owner to the exterior maintenance of the townhome Residences and their respective grounds ('Townhome Assessments"), including the establishment of reserves; b. The imposition of Townhome Assessments, including special assessments; c. Providing for care, upkeep and exterior maintenance of the townhome Residences, including the maintenance and upkeep of their respective grounds; d. Designating, hiring and dismissing the personnel necessary for the above-described maintenance functions, and contracting with any necessary persons for the performance of such duties; e. Complete authority to approve or disapprove the expenditure of any Townhome Assessments or reserves. f. The right and duty to obtain the hazard insurance policy(ies) contemplated by Article IX, Paragraph 9.1 (b) of the Declaration. g. Such other rights, powers and duties of the Board, that the Board may delegate to the Townhome Committee by majority resolution. Provided, however, that nothing in this Article shall be construed as allowing the Townhome Committee to eliminate the responsibility to properly provide for the exterior maintenance and upkeep of the town home Residences and their respective grounds, and the maintenance of insurance on the townhome structures, as described on the Declaration. 2. The funds collected from Townhome Assessments and any special Townhome Assessments shall be deposited in a separate account held by the Associaition (the "Townhome Account") and shall be separately accounted for. The Townhome Committee, or its duly authorized designee, shall have exclusive signature authority of the Townhome Account. Except as amended or supplemented hereby or previously amended or supplemented, the aforementioned terms and conditions of the Bylaws of Glen lake Upstate Homeowners Association, Inc., shall remain unchanged and in full force and effect.