---
output: pdf_document
fontsize: 11pt
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(lubridate)
library(readr)
library(dplyr)


```
# FOUNDING DOCUMENT OVERVIEW

> **Disclaimer**: this document is a list of the founding legal documents of the Glenlake Upstate Homeowners Association, inc., registered at the Spartanburg Register of Deeds. The editors believe this is the most recent version as of `r format(lubridate::today(), format="%B %d, %Y")`.

```{r dataread, include=FALSE, echo=FALSE}
foundingdocs <- read_csv("founding_documents_index.csv") %>% 
                      #rename(Deed_Book = "Deed Book") %>%
                      arrange(date) %>% 
                      mutate(Date = format(date, format="%b %d, %Y")) %>%
                      mutate(Page = formatC(Page , width=3, flag="0")) %>%
                      unite("Deed Book", c("Deed Book", Page), sep=", p.") %>%
                      select(Date, Purpose, "Deed Book")

platbook <- read_csv("platbook_index.csv") %>% 
                      #rename(Deed_Book = "Deed Book") %>%
                      arrange(date) %>% 
                      mutate(Date = format(date, format="%b %d, %Y")) %>%
                      mutate(Page = formatC(Page , width=3, flag="0")) %>%
                      unite("Plat Book", c("Plat Book", Page), sep=", p.") %>%
                      select(Date, Purpose, "Plat Book")

```

```{r dataprint, include=TRUE, echo=FALSE}
knitr::kable(foundingdocs, "pipe")

knitr::kable(platbook, "pipe")
```

