---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
```


STATE OF SOUTH CAROLINA
COUNTY OF SPARTANBURG
Glenlake Upstate Homeowners Association, Inc., Plaintiff,
v.
Joseph J. Spallone and Tammy J. Spallone, Defendants.

IN THE COURT OF COMMON PLEAS
SEVENTH JUDICIAL CIRCUIT
Civil Action No.: 2019-CP-42-03679

# ORDER

This matter came before the Court upon motion of the Plaintiff, Glenlake Upstate Homeowners Association, Inc. (“Plaintiff”), for entry of judgment against Defendants, Joseph J. Spallone and Tammy J. Spallone (collectively hereinafter, “Defendants”). The Parties stipulated to placing certain matters on the record with this Court on January 22, 2021. Based on the reasons that follow, this Court finds in favor of the Plaintiff.

# FACTS

The Complaint included the relevant well-plead factual allegations and, based on the pleadings, exhibits, and all other evidence having been made a part of the record of this case, this
Court finds as follows: 

Defendants are citizens and residents of Spartanburg County, South Carolina, and own real property located at the physical address of 118 Bridgeville Way, Boiling Springs, South
Carolina 29316 (the “Property”), which is further known and described in the records of the Spartanburg County Register of Deeds as Lot No. 280, Glenlake Subdivision, Phase 2 ‘C’.
The Declaration of Protective Covenants, Conditions and Restrictions for Glenlake Subdivision (the “Covenants”) were recorded on March 31, 2005 by Declarant, Four Bees, Inc. (“Declarant”) and Poinsett Homes, LLC (“Poinsett”). A true and correct copy of said Covenants are recorded in the Spartanburg County Register of Deeds Office in Deed Book 82-R, beginning
at Page 862. The Covenants and amendments and/or supplements thereto were made exhibits to the Complaint. As evidenced by the Covenants, the section that was initially subject to the Glenlake
Subdivision Covenants is known as Glenlake Subdivision, Phase I (“Phase I”), which is described in the records of the Spartanburg County Register of Deeds in Plat Book 157, Page
250 and which is further described in exhibit “A” and exhibit “A-1” to the Covenants. Pursuant to Article XI, Section 11.1(a) of the Covenants, the Declarant was granted the
unilateral right, privilege, and option from time to time, until seven years after recording the Covenants, to subject additional property to the provisions of the Covenants (“Annexation”).
The Covenants provide that Annexations of additional property into Glenlake Subdivision would be effective immediately upon filing for record such Supplementary Declaration describing the property being subjected to the Covenants.
On June 22, 2005, the Declarant and Poinsett caused a First Amendment to Declaration of Protective Covenants for Glenlake Subdivision (the “First Amendment”) to be recorded in the Spartanburg County Register of Deeds Office in Deed Book 83-H, beginning at Page 027. Pursuant to the First Amendment, the Declarant and Poinsett corrected a clerical or scriveners’ errors identified in Article IV, Section 4.1 of the Covenants by properly incorporating the name of the homeowners’ association associated with Glenlake Subdivision, Glenlake Upstate Homeowners Association, Inc. (the “HOA”). On November 15, 2012, the Declarant caused a Fourth Amendment to Declaration of Protective Covenants and Restrictions for Glenlake Subdivision to be recorded in the Spartanburg County Register of Deeds Office in Deed Book 102-A, beginning at Page 842 (the
“Fourth Amendment”). The Declarant recorded the Fourth Amendment to modify and amend Article IV, Section 4.3 and Article XI, Section 11.1 for the purpose of extending the period of
time which the Declarant maintained control of the Glenlake Subdivision and could unilaterally, without the consent of owners of property located in Glenlake Subdivision, annex additional
property(ies) into Glenlake Subdivision, subjecting such property(ies) to the Declaration and amendments and supplements thereto. On November 15, 2012, the Declarant caused a Supplemental Declaration of Protective
Covenants, Conditions and Restrictions for Phase 2‘C’ of Glenlake Subdivision to be recorded in the Spartanburg County Register of Deeds Office in Deed Book 102-A, beginning at Page 845
(the “Phase 2‘C’ Supplemental Declaration”). Pursuant to the Phase 2 ‘C’ Supplemental Declaration, the Declarant documented the Annexation of all lots and real properties comprising
Phase 2 ‘C’ of Glenlake Subdivision (collectively “Phase 2 ‘C’”). The lots and real property comprising Phase 2 ‘C’ are documented in a plat recorded on November 15, 2012 in the Spartanburg County Register of Deeds Office in Plat Book 167 at
Page 165 (the “Phase 2 ‘C’ Plat”).

After acquiring the lots and real property comprising Phase 2 ‘C’ and prior to selling any of the individual lots within Phase 2 ‘C’, the Declarant inaugurated the same general scheme of
development for Phase 2 ‘C’ as it had for the lots and real property annexed into Glenlake Subdivision prior to Phase 2 ‘C’. From a review of the Phase 2 ‘C’ Plat and other plats prepared for and recorded by the
Declarant, the location of the lots and real property comprising Phase 2 ‘C’ being contiguous with other sections or phases of Glenlake Subdivision and the references in the Phase 2 ‘C’ Plat
that Phase 2 ‘C’ was but one phase to a larger development (Glenlake Subdivision) evidence that
the lots and real property comprising Phase 2 ‘C’ are part of the same common plan and general
development scheme as the other sections and phases of Glenlake Subdivision.
Pursuant to the Phase 2 ‘C’ Supplemental Declaration, all lots and real property
comprising Phase 2 ‘C’ was subjected to the terms and conditions of the Covenants and all
amendments thereto.

By and through the Annexation of Phase 2 ‘C’ into Glenlake Subdivision and making
Phase 2 ‘C’ subject to the Covenants and amendments thereto, all lots and real property
comprising Phase 2 ‘C’ and the owners thereof became bound by the requirements, restrictions,
obligations, and responsibilities set forth in the Covenants and amendments thereto.
The deed (the “Deed”) conveying the Property from Enchanted Construction, LLC to the
Defendants identifies the Property as being Lot No. 280 of Phase 2 ‘C’. Further, the Property is
identified in the Phase 2 ‘C’ Plat.

Pursuant to the Deed, the conveyance of the Property from Enchanted Construction, LLC
(“Enchanted”) to the Defendants was subject to the Easements, Restrictions, Covenants, and
Conditions recorded in the Office of the Register of Deeds/Clerk of Court for Spartanburg
County.

Pursuant to the deed conveying ownership of the Property to Enchanted Construction,
LLC from Declarant (the “Enchanted Deed”), the conveyance to Enchanted Construction, LLC
was subject to all covenants, restrictions, easements, rights of way, and other matters of record
and such matters as would be shown by a current plat and inspection affecting the Property. The
Enchanted Deed was recorded on September 18, 2014 in the Spartanburg County Register of
Deeds Office in Deed Book 107-B at Page 425.

The Enchanted Deed was recorded and made public record prior to Enchanted
Construction, LLC conveying the Property to Defendants. Prior to Enchanted Construction, LLC
conveying the Property to Defendants, the Covenants and amendments and supplements thereto
were recorded in the Spartanburg Register of Deeds Office.

Prior to selling any of the lots and real property comprising Phase 2 ‘C’, to include the
Defendants’ Property, the Declarant caused the Covenants and amendments and supplements
thereto to be recorded in the Spartanburg County Register of Deeds Office, thereby making the
same public records and placing the Defendants on notice that the Property is an integral part of
Glenlake Subdivision, that there is a HOA associated with Glenlake Subdivision, that the
Property and the Defendants are subject to annual HOA fees, and that there are certain
subdivision amenities and use restrictions that accompanied ownership of the Property.
The Defendants were granted and accepted the Property subject to and with knowledge of
the Covenants and the common plan and general development scheme of Glenlake Subdivision
as reflected in the Phase 2 ‘C’ Plat. Further, after closing on the Property, and on more than one
occasion, the annual HOA dues owed to Plaintiff pursuant to the Covenants were paid by
Defendants.

Glenlake Subdivision offers amenities to the owners of lots located within Phase 2 ‘C’,
including the Defendants, and all other Phases of Glenlake Subdivision. The amenities offered to
the lots and owners thereof, including the Defendants, include, without limitation, a pool facility,
clubhouse, roads and sidewalks, playground, exterior lighting, landscaping of common areas, use
of common areas, gated and manicured entrances with structures and appurtenances,
retention/detention ponds, and established rules and guidelines (collectively the Glenlake
Subdivision “Amenities”), the same being owned and maintained by Glenlake.

Since accepting their Deed to the Property, and on more than one occasion, the
Defendants have enjoyed access to, used, or have otherwise benefited from one or more of the
Glenlake Subdivision Amenities.

Despite having actual knowledge that the Property and their use and ownership thereof is
subject to the Covenants, the Defendants have failed or otherwise refused to pay the 2019 annual
assessments as required pursuant to Article V of the Covenants.
The Defendants have: (a) notified the the Plaintiff of their position that their Property and
ownership and use thereof is not subject to the Covenants; and (b) failed to pay annual
assessments due for 2019.

Defendants did not contest or reject that the Property and their use and ownership thereof
is subject to the Covenants until October 2018, over three years after purchasing the Property,
using or otherwise enjoying the Glenlake Subdivision Amenities, and after paying assessments in
accordance with Article V of the Covenants.

# APPLICABLE LAW

The most common means of creating restrictive covenants are by (i) deed, including by
reference to recorded plat in said deed, (ii) declaration, and (iii) by implication from a general
plan or scheme of development. A detailed statement of the rule appears in one South Carolina
cases:

“[W]here a common grantor opens a tract of land to be sold in lots and blocks,
and, before any lots are sold, inaugurates a general scheme of improvement for
the entire tract intended to enhance the value of each lot, and each lot,
subsequently sold by such grantor, is made subject to such scheme of
improvement, there is created and annexed to the entire tract what is termed a
negative equitable easement, in which the various purchasers of lots have an
interest, and between whom there exists mutuality of covenant and
consideration.”

The earliest method of creating restrictive covenants was by deed. See, e.g., McCullough v.
Urquhart, 248 S. C. 348, 149 S. E. 2d 909 (1966); Stanton v. Gulf Oil Corp., 232 S. C. 148, 101 S. E.
2d 250 (1957); Forest Land Co. v. Black, 216 S. C. 255, 57 S. E. 2d 420 (1950). “Even a deed invalid
on various technical grounds may nevertheless create restrictions.” McCullough v. Urquhart, 248 S.
C. 348, 149 S. E. 2d 909 (1966). Restrictions created by deed may differ significantly in nature from
those created by plat or declaration, in that the former apply to lots individually, and the latter apply
to the subdivision as a whole. See Stanton v. Gulf Oil Corp., 232 S. C. 148, 101 S. E. 2d 250 (1957).
A number of South Carolina cases illustrate the creation of restrictive covenants by reference
in a deed to a recorded plat. See, e.g., Circle Square Co. v. Atlantis Dev. Co., 267 S. C. 618, 230 S.
E. 2d 704 (1976); Epps v. Freeman, 261 S. C. 375, 200 S. E. 2d 235 (1973); Hamilton v. CCM, Inc.,
274 S. C. 152, 263 S. E. 2d 378 (1980); Briarcliff Acres v. Briarcliff Realty Co., 262 S. C. 599, 206
S. E. 2d 886 (1974). Such areas must, however, be clearly designated. “Where property is sold by
reference to a plat on which streets, parks, and open areas are shown, an easement in such areas is
created in the grantee.” Epps v. Freeman, 261 S. C. 375, 200 S. E. 2d 235 (1973); Cason v. Gibson,
217 S. C. 500, 61 S. E. 2d 58 (1950) (roads); Diseker v. Eau Claire Land & Imp. Co., 86 S. C. 281,
68 S. E. 529 (1910) (parks or open areas).
Restrictive covenants may also be created by recording a declaration of restrictive covenants.
See, e.g., Flinkingshelt v. Johnson, 258 S. C. 77, 187 S. E. 2d 233 (1972); Sprouse v. Winston, 212 S.

Edwards v. Surratt, 228 S. C. 512, 520, 90 S. E. 2d 906, 909 (1956). Accord McDonald v. Welborn, 220 S. C. 10, 66 S. E. 2d
327 (1951); Sprouse v. Winston, 212 S. C. 176, 46 S. E. 2d 874 (1948); Stanton v. Gulf Oil Corp., 232 S. C. 148, 101 S. E. 2d
250 (1957); Hamilton v. CCM, Inc., 274 S. C. 152, 263 S. E. 2d 378 (1980); Williams v. Cone, 249 S. C. 374, 154 S. E. 2d 682
(1967); Easterly v. Hall, 256 S. C. 336, 182 S. E. 2d 671 (1971); Gibbs v. Kimbrell, 311 S.C. 261, 428 S.E.2d 725 (Ct. App.
1993). C. 176, 46 S. E. 2d 874 (1948). Where a grantor recorded an agreement containing restrictions and a
plat of a residential subdivision, and later executed deeds that did not contain the restrictions, South
Carolina courts have ruled that the failure to mention the restrictions in the deeds was of no legal
significance since the restrictions were of record. Flinkingshelt v. Johnson, 258 S. C. 77, 187 S. E. 2d
233 (1972).

Another important method of creating restrictive covenants is by implication from a
uniform scheme of development. A model case is one in which a parcel of property is developed
more or less uniformly by an owner, but restrictions are either omitted, or made effective only as
to some lots, or a portion of the area. The courts of South Carolina and most other states have
resolved this situation by implying an obligation in appropriate cases to observe a plan of
development that was in effect prior to any purchases from the common grantor.
Restrictive covenants may impliedly be created by a plan of development. See, e.g.,
Edwards v. Surratt, 228 S. C. 512, 90 S. E. 2d 906 (1956); Bomar v. Echols, 270 S. C. 676, 680,
244 S. E. 2d 308, 310 (1978); Stanton v. Gulf Oil Corp., 232 S. C. 148, 101 S. E. 2d 250 (1957).
In the absence of effective restrictions, a recital in a deed that property is subject to restrictions is
one factor which may furnish evidence of a common scheme. Such a recital is, however,
unnecessary where a declaration of restrictive covenants has been recorded. Flinkingshelt v.
Johnson, 258 S. C. 77, 187 S. E. 2d 233 (1972). Neither the restricting of every lot in a
subdivision, nor the absolute identity of restrictions upon every lot, is essential to the existence
of a neighborhood scheme. Martin v. Cantrell, 225 S. C. 140, 81 S. E. 2d 37 (1954); Pitts v.
Brown, 215 S. C. 122, 54 S. E. 2d 538 (1949).

For a reciprocal negative easement to arise by implication, the implication must be plain
and unmistakable. Shoney’s, Inc. v. Cooke, 291 S. C. 307, 353 S. E. 2d 300 (Ct. App. 1987);
Charping v. J. P. Scurry & Co., 296 S. C. 312, 372 S. E. 2d 120 (Ct. App. 1988). In determining
whether a reciprocal negative easement exists, the court considers the language in the deed and
the surrounding circumstances. Shoney’s, Inc. v. Cooke, 291 S. C. 307, 353 S. E. 2d 300 (Ct.
App. 1987); Nance v. Waldrop, 258 S. C. 69, 187 S. E. 2d 226 (1972). The restricting of every
lot in the subdivision is not essential to the existence of a scheme. Easterly v. Hall, 256 S. C.
336, 182 S. E. 2d 671 (1971); Pitts v. Brown, 215 S. C. 122, 54 S. E. 2d 538 (1949). Deeds
containing restrictions may afford constructive (or actual) notice to those purchasing
subsequently. McDonald v. Welborn, 220 S. C. 10, 66 S. E. 2d 327 (1951).

Covenants are contractual in nature. To enforce a restrictive covenant, a party must show that
the restriction applies to the property either by the covenant’s express language or by plain
unmistakable implication. See Sea Pines Plantation Co. v. Wells, 294 S.C. 266, 270-71, 363 S.E.2d
891, 894 (1987). A Court shall enforce restrictive covenants unless they are indefinite or contravene
public policy. See id. Restrictive covenants are contractual in nature, and thus, the language used in
restrictive covenants is to be construed according to its plain and ordinary meaning. See Hardy v.
Aiken, 369 S.C. 160, 166, 631 S.E.2d 539, 542 (2006). “The court may not limit a restriction in a
deed, nor, on the other hand, will a restriction be enlarged or extended by construction or implication
beyond the clear meaning of its terms[”] even to accomplish what it may be thought the parties
would have desired had a situation which later developed been foreseen by them at the time when the
restriction was written. Taylor, 332 S.C. at 4, 498 S.E.2d at 864.

# FINDINGS

## A. Plaintiff’s Legal Claims

### I. Declaratory Judgment

In the Complaint, the Plaintiff requested a judicial declaration in accordance with S.C.
Code §§ 15-53-10 et seqq. that, inter alia: (i) the property and individual lots comprising Phase 2
‘C’ section of the Glenlake Subdivision are subject to the Declaration of Protective Covenants,
Conditions and Restrictions for Glenlake Subdivision having been recorded on March 31, 2005
in the Spartanburg County Register of Deeds Office in Deed Book 82-R, beginning at Page 862,
and amendments and/or supplements thereto; and (ii) that as a result, the Defendants’ and their
Property are subject to the Covenants and form a part of Glenlake Subdivision.

As to the Plaintiff’s First Cause of Action this Court finds:
(i) The property comprising Glenlake Subdivision, including those individual lots
and/or parcels of land in Phase 2 ‘C’ share a common owner (the Declarant) in the
chain of title to such properties;
(ii) The Declarant caused certain plats to be prepared which reflect the boundaries of
Phase 2 ‘C’ to be within Glenlake Subdivision and that the roads and
infrastructure of Phase 2 ‘C’ would be tied into existing roads and infrastructure
of Glenlake Subdivision;
(iii) That the Declarant of Glenlake Subdivision sold multiple parcels and/or lots of
land in Phase 2 ‘C’ to Enchanted for the purpose of constructing single family
residences which would be sold to individuals and families who would occupy the
same;
(iv) Enchanted constructed a residence on the Property and conveyed title to the same
to the Defendants. The Defendants purchased the Property subject to, inter alia,
the Covenants, restrictions, easements, rights of way, and limitations that were
made of record at the time of taking ownership of the Property;
(v) The Declaration of Protective Covenants, Conditions and Restrictions for
Glenlake Subdivision and amendments and supplements thereto were made of
record prior to the Defendants being conveyed ownership of the Property;
(vi) In order to access any lot or property located in Phase 2 ‘C’ of Glenlake
Subdivision, the owners thereof must travel the roads and sidewalks located inside
of entry features (e.g. subdivision gates, signage, landscaping, and lighting) of
Glenlake Subdivision;
(vii) The residences constructed within phase 2 ‘C’ of Glenlake Subdivision are of
similar design and appearance to other residences located in Glenlake Subdivision
such that it apparent that the Declarant intended for those properties comprising
Phase 2 ‘C’ to be a part of a common scheme of development applicable to all of
Glenlake Subdivision;
(viii) The Glenlake Subdivision and all phases thereof, including Phase 2 ‘C’, conform
to a general plan and/or scheme of development;
(ix) The Glenlake Subdivision contains various amenities that are owned and
maintained by Plaintiff but are commonly shared and used by the owners of lots
within Glenlake Subdivision;
(x) The Covenants empower the Plaintiff to charge and/or impose assessments on lots
located within Glenlake Subdivision and upon taking ownership of the Property;
(xi) From taking ownership of the Property until January 2019, Defendants paid
assessments to Plaintiff in accordance with the Covenants; and
(xii) In addition to intentionally and purposefully availing themselves to the Covenants
by taking ownership of the Property and paying assessments to the Plaintiff from
2015 until 2019, Defendants were provided access to, use, and benefit from
Glenlake Subdivision roads, sidewalks, stormwater facilities and other
infrastructure, and subdivision Amenities.

Based on the foregoing and regardless of the timeliness of the Declarant’s filing of the
fourth amendment to the Covenants which extended the Declarant’s unilateral right to annex
property into the Glenlake Subdivision, this Court finds that the property and individual lots
comprising Phase 2 ‘C’ section of the Glenlake Subdivision are subject to the Declaration of
Protective Covenants, Conditions and Restrictions for Glenlake Subdivision having been
recorded on March 31, 2005 in the Spartanburg County Register of Deeds Office in Deed Book
82-R, beginning at Page 862, and amendments and/or supplements thereto. This Court further
finds that, as a result, the Defendants’ and their Property are subject to the Covenants, as
amended and supplemented, and form a part of Glenlake Subdivision.

### II. Breach of Contract

The Plaintiff also requested damages under its Breach of Contract claim against the
Defendants for their failure to pay HOA dues. As outlined in the Complaint, the basis of the
Plaintiff’s Breach of Contract claim is that:
(i) The Declaration of Protective Covenants, Conditions and Restrictions for
Glenlake Subdivision is a binding contract upon the Defendants;
(ii) Article V of the Covenants outlines the assessment obligations associated with
Defendants’ ownership and use of the Property;
(iii) In accordance with Article V of the Covenants, all lot owners within Glenlake
Subdivision, including the Defendants, are subject to an annual assessment;
(iv) In accordance with Article V of the Covenants, the failure of a lot owner to fulfill
its assessment obligations subjects such lot owner to late charges, interest and
attorneys’ fees incurred for enforcement;
(v) In accordance with Article V of the Covenants, the failure of a lot owner to meet
its assessment obligations subjects such property owner to, inter alia, personal
liability; and
(vi) Defendants have breached the Covenants by failing to pay annual assessments for
years 2019 and 2020.

As to the Plaintiff’s Second Cause of Action this Court finds:
(i) The Declaration of Protective Covenants, Conditions and Restrictions for
Glenlake Subdivision are applicable to and binding on the Defendants and their
Property;
(ii) That the language and provisions contained in the Covenants are clear and
unambiguous;
(iii) Pursuant to the Covenants, the Defendants are obligated and responsible for
payment of assessments to Plaintiff;
(iv) In addition to the Defendants obligation and responsibility to timely and fully pay
assessments to Plaintiff, in the event of a failure to timely and fully pay
assessment to Plaintiff in accordance with the Covenants, the Defendants are
personally liable for late charges, interest and attorneys’ fees incurred by Plaintiff
for enforcement of the Covenants resulting from Defendants failure to pay
assessments; and
(v) Defendants failed to timely and fully remit payment of assessments justly due and
owing to Plaintiff pursuant to Article V of the Covenants for the years 2019 and
2020 and, as a result, are in breach of the Covenants.

Based on the foregoing findings of this Court that the Defendants’ and their Property are
subject to the Covenants, as amended and supplemented, the Defendants are obligated and
responsible for payment of assessments to the Plaintiff as set forth in the Covenants. This Court
finds that the Defendants have failed to honor their express obligations and responsibilities to
pay assessments to the Plaintiff and, as a result, have breached the Covenants. Accordingly, the
Defendants are liable to Plaintiff for past due assessments in the amount of One Thousand Four
Hundred Eighty-Two and 27/100 ($1,482.27) Dollars. As of the date of this Order, the
Defendants have remitted payment of past due assessments to Plaintiff and have otherwise
resolved and/or satisfied the damages sought by Plaintiff in its Second Cause of Action.

### III. Reciprocal Negative Easement

Analogous and in the alternative to the Plaintiff’s First Cause of Action seeking
declaratory judgment, the Plaintiff seeks to establish that the Covenants are applicable to and
binding on the Defendants and the Property under the theory that reciprocal negative easement.
In light of this Court’s findings on the First and Second Causes of Action, the the facts at
issue and damages sought under Plaintiff’s Third Cause of Action have effectively been
adjudicated. However, this Court finds that it would be instructive to set forth the findings which
establish, under the theory of reciprocal negative easement, sufficient facts and evidence exists to
support that the Property falls within the common scheme of development of Glenlake
Subdivision such that the Property and Defendants are subject to the Covenants and are
contractually bound to honor, inter alia, the obligation and/or responsibility to timely and fully
remit payment of assessments charged by Plaintiff in accordance with Article V of the
Covenants. 

Accordingly, this Court finds as follows:
(i) The lots, tracts, and parcels of real property comprising Glenlake Subdivision
including, but not limited to, the Property, were owned by the Declarant and its
assigns;
(ii) The Declarant was the common grantor of the real property comprising the
Subdivision and all phases thereof;
(iii) The Declarant owned the property comprising Glenlake Subdivision with the
intent to develop, and did develop, the same into a multi-phase subdivision of
single-family residences together with other improvements and amenities
intended to enhance the value of each separate portion of real property comprising
Glenlake Subdivision (collectively the “Common Scheme of Development”);
(iv) On November 15, 2012, seven years and eight months after the recording of the
Covenants, the Declarant caused a fourth amendment to the Covenants to be
recorded in the Spartanburg County Register of Deeds in Deed Book: 102-A,
beginning at Page: 842 (the “Fourth Amendment”);
(v) The Fourth Amendment extended the period of time the Declarant retained the
right to unilaterally annex additional properties in to Glenlake Subdivision make
the same subject to the Covenants;
(vi) Glenlake Subdivision was developed, as intended by the Declarant, in multiple
phases of single-family residences and amenities located within the phases
comprising Glenlake Subdivision, including the Defendants Property in Phase 2
‘C’, and all other Phases of Glenlake Subdivision. The amenities offered to the
lots and owners thereof, including the Defendants, include, without limitation, a
pool facility, clubhouse, roads and sidewalks, playground, exterior lighting,
landscaping of common areas, use of common areas, manicured entrances with
structures and appurtenances, retention/detention ponds, and established rules and
guidelines (collectively the Glenlake Subdivision “Amenities”);
(vii) In furtherance of the Common Scheme of Development, the Declarant established
and recorded the Covenants, together with amendments and supplements thereto.
The Declarant intended to further evidence the Annexation of Phase 2 ‘C’ into the
Glenlake Subdivision by filing the Phase 2 ‘C’ Supplemental Declaration.
Pursuant to the Phase 2 ‘C’ Supplemental Declaration, all lots and real property
comprising Phase 2 ‘C’ were subjected to the terms and conditions of the
Covenants and all amendments thereto;
(viii) Pursuant to the Declarant’s deed conveying the Property to Enchanted, the
conveyance was subject to all covenants, restrictions, easements, rights of way,
and other matters of record and such matters as would be shown by a current plat
and inspection of the Property. The Declarant’s deed to Enchanted was recorded
after the Declarant’s attempt to unilaterally annex properties comprising Phase 2
‘C’ into Glenlake Subdivision;
(ix) The Declarant’s deed to Enchanted was made of record prior to Enchanted’ s
conveyance of the Property to the Defendants;
(x) The Defendants were conveyed and accepted the Property subject to and with
knowledge of the Covenants and the Commons Scheme of Development for
Glenlake Subdivision;
(xi) During their ownership of the Property, the Defendants have benefited from
Common Scheme of Development and Glenlake Subdivision Amenities. Further,
from the date the Defendants were conveyed the Property until January 2019, the
Defendants remitted payment of assessments to the Plaintiff for the costs
associated with the Defendants’ use and the benefits received from use of the
Glenlake Subdivision Amenities; and
(xii) The Defendants purposefully and intentionally availed themselves to the rights,
responsibilities and obligations set forth in the Covenants by purchasing the
Property with actual and/or constructive knowledge of the Covenants, making use
of and benefitting from use of Glenlake Subdivision Amenities, and by paying
annual assessments as provided in the Covenants for years 2015, 2016, 2017, and
2018.

Based on the foregoing, this Court finds that the Declarant established a common scheme
of development for Glenlake Subdivision and developed the property comprising Glenlake
Subdivision to conform with the Declarant’s intended common scheme. The individual parcels,
tracts, sections, and phases of land comprising Glenlake Subdivision are referenced in various
plats which indicate that the properties form Glenlake Subdivision and are a part of a planned
development consisting of single-family residences. Further, the property comprising Glenlake
Subdivision are accessed by crossing Glenlake Subdivision entry features and by use of common
and shared infrastructure.

This Court further finds, regardless of the timeliness of the Declarant’s filing of the
fourth amendment to the Covenants which extended the Declarant’s unilateral right to annex
property into the Glenlake Subdivision, when viewing a totality of the facts and circumstances, it
is clear that the Property was once owned by the Declarant (a common owner), the the
Covenants were of record at the time the Defendants took ownership of the Property, the
Defendants knew or should have known that the Property is subject to the Covenants and was
intended to form a part of the Glenlake Subdivision, the Defendants benefited from and made use
of Glenlake Subdivision infrastructure and Amenities, and the Defendants until 2019 paid
assessments to the Plaintiff as provided by the Covenants.

Accordingly, to the extent this Court would have found that the Defendants and their
Property were not expressly subject to the Covenants, this Court would find and order that: (i)
the real property and lots comprising Phase 2 ‘C’ of the Glenlake Subdivision, including the
Defendants’ Property, are subject to implied covenants and/or negative reciprocal easements; (ii)
by virtue of their ownership interest in the Property, the Defendants are subject to implied
covenants and/or negative reciprocal easements; and (iii) Defendants are obligated to pay all past
due assessments owed to the Plaintiff associated with the Defendants ownership of the Property
and the benefits conferred to the Defendants by use of Glenlake Subdivision infrastructure and
amenities.

# CONCLUSION

The facts and law as cited above makes clear that the Plaintiff is entitled to the judicial
declaration that the Defendants’ and their Property are subject to the Covenants, as amended and
supplemented, and form a part of Glenlake Subdivision. As such, the Plaintiff is entitled to
receive, and the Defendants are obligated to pay, the amount of One Thousand Four Hundred
Eighty-Two and 27/100 ($1,482.27) Dollars as payment of the past due assessments owed. As of
the date hereof, Defendants have remitted payment of One Thousand Four Hundred Eighty-Two
and 27/100 ($1,482.27) Dollars to Plaintiff, thereby satisfying past due assessments owed to
Plaintiff as of December 31, 2020.

The Defendants shall continue to be bound by the Declaration of Protective Covenants,
Conditions and Restrictions for Glenlake Subdivision having been recorded on March 31, 2005
in the Spartanburg County Register of Deeds Office in Deed Book 82-R, beginning at Page 862,
and amendments and/or supplements thereto for so long as the Defendants, jointly or severally
hold any ownership interest in the Property.

AND IT IS SO ORDERED.
Presiding Judge
January 22, 2021 Seventh Judicial Circuit
Spartanburg, South Carolina

Case Caption: Glenlake Upstate Homeowners Association, Inc. VS Joseph J Spallone, defendant, et al
Case Number: 2019CP4203679
Type: Order/Other

IT IS SO ORDERED!
s/J. Derham Cole 2053
Electronically signed on 2021-03-29 16:11:35 page 20 of 20
ELECTRONICALLY FILED - 2021 Mar 29 4:41 PM - SPARTANBURG - COMMON PLEAS - CASE#2019CP4203679