---
title: "Board and Association Meetings"
output: 'pdf_document'
bibliography: ../bibliography/biblio.json
csl: ../bibliography/numeric.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(lubridate)

TOTALHOMES =  482
```


> Author: Rob Hanssen

> Version: `r format(lubridate::today(), format="%B %d, %Y")`

# Purpose

The legal manner of conducting Association business is through the open Board and Association meetings. Meetings should be efficient in its use of time and topics for discussion. This guide provides some guidelines based on the experiences of the past years.

\tableofcontents
\newpage

# Types of meetings

## Organizational Meeting

The Organizational Meeting[@by0308] is the first board meeting after the elections and is used to appoint or elect the Officers of the Board (President, Vice President, Treasurer, Secretary). It is best to use this meeting to set the meeting schedule for the rest of the year and communicate this schedule via regular mail.

## Regular Meetings of the Board of Directors

There should be at least one meeting per quarter,[@by0309] i.e. four meetings per year. If there are no deviations from the schedule set during the Organizational Meeting and communicated via regular mail, no further notice is required.[@by0309] For convenience, the meetings can be announced on the Association website. During regular meetings, a majority of the Board members needs to be present to conduct any business.[@by0312]

Historically, the Board has met monthly to keep the flow of information within the Board and to and from the homeowners going smoothly.

## Special Meetings of the Board of Directors

There are restrictions on who can call a Special Meeting of the Board:[@by0310]

1)  The President or Vice President
2)  Any two Directors

The Special Meeting of the Board must be announced to Directors at least four days before the actual meeting by mail, or 48 hours before the meeting if announced by personal delivery, telephone or e-mail, and the meeting notice must include the topics. No other topics than those announced in the notice can be discussed. Special Meetings of the Board have the same requirements as Regular Meetings of the Board.

## Special Meetings of the Association

There are restrictions on who can call a Special Meeting of the Association:[@by0203]

1)  The President
2)  The Board, by passing a resolution
3)  A homeowner-led petition with at least 5% support from the Total Association Vote (`r TOTALHOMES %/%20` members)

The Special Meeting must be announced at least ten days before the actual meeting, and the meeting notice must include the topics. No other topics than those announced at the notice can be discussed. The quorum for holding a Special Meeting of the Association is 25% of the Total Association Vote (i.e. `r TOTALHOMES %/% 4` members) who can be present in person or present by proxy to another person.[@by0209]

The budget is subject to a specific procedure.[@cov0507] After approval of the budget by the Board of Directors, homeowners can petition the Board to reject the approved budget by passing a budget rejection vote with at least 50% support of the Total Association Vote (`r TOTALHOMES %/% 2` members) at a Special Meeting of the Association. If the rejection can proceed, the budget will automatically fall back to the budget of the previous year until the Board can approve a new budget.

Removal of Directors from the Board of Directors[@by0306] can be done at any Regular or Special Meeting of the Association by passing a director removal vote with at least 50% support of the Total Association Vote (i.e. `r TOTALHOMES %/% 2` members). The contested Director must be given ten days notice before the vote and must be given the opportunity to be heard before the vote. If the Director is removed in this manner, a new Director must be elected by the homeowners. Other circumstances under which Directors can be removed from the Board by the remaining Board Members are listed in the Bylaws. A Director removed under these circumstances can be replaced by Board appointment.

## Annual Meetings of the Association

The Annual Meeting is covered in another guide.

# Proxies

In case members cannot be physically present at an Association meeting, they can assign a proxy to another person[@by0208] by sending a proxy form to the Secretary of the Board of Directors. Proxies can be assigned to any other member of the Association in good standing. The proxy must be specific in the duration of the assignment and the powers transferred. Examples of both can be found in the table.

Proxies can also be revoked at any time by the member issuing the proxy by notifying the Secretary. Proxies will also be revoked automatically in case of:

-   Sale of the lot by the issuing member or the proxy member

-   Death or judicially declared incompetence of the member

-   11 months after the proxy was originally assigned

+----------------------------------+---------------------------------------------+
|                                  | Example                                     |
+==================================+=============================================+
| Proxy duration                   | A specific meeting                          |
+----------------------------------+---------------------------------------------+
|                                  | All Association meetings during the year    |
+----------------------------------+---------------------------------------------+
| Powers transferred               | Presence at the meeting to determine quorum |
+----------------------------------+---------------------------------------------+
|                                  | Voting power                                |
+----------------------------------+---------------------------------------------+

There is no limit on how many proxies a member can be assigned to. For all intents and purposes, the member represents all of their proxies during the meeting to the extent of the powers transferred.

# The agenda (Regular Meeting of the Board)

The process for setting the agenda is best started approximately two weeks before the meeting. The President or the Secretary sends out a draft agenda based on the current topics of business, typical activities during the time of year, new topics since the last meeting and committee reports. Other Directors can add items to the agenda. The agenda should be finalized about one week before the meeting and published on the website.

The agenda can be setup in a format like this:

1)  Call to order (President)
2)  Reading of the minutes of the previous meeting and vote for approval (Secretary)
3)  Review of the treasury report and vote for approval (Treasurer)
4)  Current business (Topic Owners)
5)  New business (Topic Owners)
6)  Open Forum (Homeowners)
7)  Adjournment to Executive Session (President)
8)  Adjournment to the next meeting (President)

## Call to order

This serves as the official opening of the meeting. This indicates that only Board Directors can request to speak, unless others expressly allowed to do so by the meeting chair.[@by0314]

## Reading of the minutes of the previous meeting and vote for approval

In the strictest sense of meeting organization according to Robert's Rules, the minutes of the previous meeting must be read aloud by the Secretary or a designee before they can be approved by the full Board. To make the meeting more efficient, the minutes can be sent out to all Board Directors before the meeting.

To approve the minutes without reading aloud, the Secretary can make a motion to dispense with the reading of the minutes and approve the minutes for publishing.

## Review of the Treasury Report and vote for approval

The Treasurer can review the treasury report in a manner most suitable to their personal preference at the regular meetings. Typically, the amount of income and spending in the previous month and year-to-date are reviewed. In case there are unexpected or high expenses, these are mentioned.

To approve the treasury report, any Director can make a motion.

## Current business

Any business that was tabled for further research or follow-up in previous meetings can be handled in this part of the session. Potential action in this section can be to table the topics until the next meeting or to a date most suitable without action; a vote to table the matter for further research or other actions; a vote to conclude the matter or a vote to dismiss the matter.

The Topic Owner can be a Director, a Committee Member or any person who is designated as the Topic Owner. It is the Topics Owner's responsibility to handle any progress on the matter at hand.

## New business

New business can be added to the meeting agenda by any Director, or by the President approving a request from any homeowner to add a topic to the agenda. Requests for topics by homeowners is best done up to a week before the meeting, so it can be included on the agenda in a timely fashion.

## Open Forum 

Historically, the open forum has been added to the agenda, either at the beginning or at the and of the public part of the meeting. The Open Forum give homeowners the opportunity to bring up issues for the general interest of the Association in a two-minute time slot. At the discretion of the chair, more time can be added if it is in the interest of the discussion.

## Adjournment to Executive Session 

An Executive Session[@by0315] is a part of the meeting which is open only to the Board of Directors and persons specifically invited to this session. The nature of all topics discussed at the Executive Session should be announced at the public session and are limited to personnel matters, litigation in which the Association is or may become involved and orders of business of a similar nature. The discussion within an Executive Session is considered confidential and cannot be shared outside the meeting, unless decided to do so by the Board of Directors.

## Adjournment to the next meeting 

The President makes a motion to conclude this session.

# Voting at meetings 

Business is conducted according to Robert's Rules of Order.[@by0602] The implications for the decision-making process are that all voting matters are introduced in the form of a motion by a Director. This motion needs to be seconded by another Director. After discussion, a vote can be held to accept or reject the motion.

## Making a motion

A Director makes a motion in the form "I move that ...". In case the motion is concise and clear, this can be done at the meeting. If the motion contains many clauses and sub-clauses, it is advised to send out motions to all Directors before the meeting.

## Second a motion 

A Director, other than the one making the motion, can state "I second this motion". This only means the second Director finds the topics worthy of discussion, not that the second Director would vote in favor of the motion, should it come to a vote. If a motion is not seconded, it is automatically rejected.

## Discussion 

After the motion has been seconded, the President can open the motion for discussion among the Directors. The discussion can be informational in nature or can be used to modify the original motion. To amend the original motion, a Director can make a motion in the form "I move to amend the motion to...". This move to amend is treated as any other move would be with secondment and further discussion. At the end of discussion, the amendment must be approved by vote. After discussion among the Directors is completed, the President can invite comments from the homeowners. The end of discussion can result in a vote or in tabling the matter until further notice.

## Voting 

The President repeats the (amended) motion and asks for votes in favor and against the motion. If there is a majority of the Directors present in favor of the motion, the motion passes.

Examples:

|                                                                                                                                       |                         |
|---------------------------------------------------------------------------------------------------------------------------------------|-------------------------|
|  In a board with seven members, seven are present. Five members vote in favor, while two vote against.                                |  The motion passes.     |
| In a board with seven members, four are present. Three members vote in favor while one votes against.                                 | The motion passes.      |
| In a board with seven members, four are present. Two members vote in favor, while two vote against.                                   |  The motion is rejected.|
| In a board with seven members, seven are present. Three members vote in favor, while three vote against and one abstains from voting. | The motion is rejected. |

Independent whether a motion passes or is rejected, it is preferable that the same motion or a motion of similar content is not discussed in that session to prevent Directors from forcing the matter at hand by making the same or similar motion multiple times.

\newpage
# References
