# Article XVI

## Variances
Notwithstanding anything to the contrary contained herein, the Declarant and the Board or its designee shall be authorized to grant individual variances from any of the provisions of this Declaration, the By-Laws and any rule, regulation, or use restriction promulgated pursuant thereto if it determines that waiver of application or enforcement of the provision in a particular case would not be inconsistent with the overall scheme of development for the Community.

# Article XVII

## Arbitration
ALL MEMBERS OF THE ASSOCIATION AGREE THAT ANY DISPUTE ARISING BETWEEN THE MEMBERS AND THE ASSOCIATION OR ANY DISPUTE ARISING BETWEEN THE ASSOCIATION AND THE DECLARANT OR "POINSETT HOMES. LLC", SHALL BE RESOLVED THROUGH ARBITRATION PURSUANT TO THE RULES PROMULGATED BY THE AMERICAN ARBITRATION ASSOCIATION. THE PARTIES AGREE THAT JURISDICTION AND VENUE FOR ANY DISPUTE RESOLUTION HEREUNDER SHALL BE SPARTANBURG COUNTY SOUTH CAROLINA.

# Article XVIII

## Capitalization of Association
Upon acquisition of record title to a Lot by the first Owner other than Declarant or a builder, a
contribution of $100.00 ("initiation Fee") shall be made by or on behalf of the purchaser to the
Association as set forth below. The Initiation Fee shall be in addition to, not in lieu of, any
annual or special assessments. The Initiation Fee shall be payable at closing, shall not be
prorated, and the Association shall have all rights under the Declaration for enforcement of
assessments if it is not paid. The initiation Fee referred to in this paragraph is payable only one
time, and will not be charged subsequent purchasers of a Lot once paid.