# Animals and the Fair Housing Act

The Covenants state in Section 8.21
- Two animals per lot (excluding small rodents, fish, or any caged animals that are normally not taken outside)
- All animals must be on a leash, unless they are on the owner's property
- All animal waste must be removed immediately from owners' lots and common areas.
- Animals living in the Town Home area have an additional weight restriction of max. 50 lbs.

Service animals are excluded from the number of animals per lot. The  Association can require a homeowner to provide proof that he/she requires a service, companion, or therapy animal. This proof generally consists of a letter from a licensed medical doctor confirming the type of animal, or a specific animal, needed to accommodate a homeowner’s disability.

In some cases, as when a homeowner is visibly blind or in a wheelchair, the board may not need to request proof of a disability (and it could seem inappropriate to do so). If a homeowner is unwilling or unable to provide proof of his/her need for a reasonable accommodation, then the association could prohibit the dog unless and until proper evidence of a need for a reasonable accommodation is received. However, the board and management have no right to know what the homeowner’s specific disability is, as medical records are generally private 