# Annexation

- What is going on with this annexation? Why did I receive a letter?

When the developer started our neighborhood, he bought a piece of undeveloped property. Pieces of this property or phases were added to the Glen Lake neighborhood and its governing body (Glenlake Upstate Homeowners Assocation Inc.) in phases. In addition, areas like the roads, the lake, the entrances, the pool and club house, etc. were designated as common areas and subsequently conveyed to the association for typically $1 each.

The developer had until March 2012 to add all phases. The initial phases were added correctly since the developer had the authority to add (i.e. annex) these phases to the neighborhood. Later phases (after March 2012) were added incorrectly as the right of the developer to annex new property into the neighborhood had expired and the developer failed to extend that authority prior to that right expiring.

After turning the neighborhood over to the homeowners in early 2018, the elected board noticed the discrepancy and started to investigate and correct the potential issues. This discrepancy does not affect your ownership of your property, our efforts are to correct a clerical error.

- Why did I receive a consent form?

You are in a phase that was annexed incorrectly. In order to correct the paperwork discrepancy, you can sign the consent form stating that you agree to be part of the neighborhood. Unfortunately, due to the rules in the governing documents, this request has to be approved by the other homeowners who are in the older (correctly annexed) phases.

Note that the consent form needs to be notarized.

- Why did I receive a ballot?

You are in a phase that was correctly annexed by the neighborhood Association. Due to the rules in the governing documents, requests by homeowners who would like to become part of the neighborhood have to be approved by the other homeowners who are in the correctly annexed phases. Your ballot gives you the opportunity to accept the entire group of folks in the incorrectly annexed phases who agree to be part of the neighborhood. The rules state that 2/3rds of the initial 285 lot owners (i.e. 190) need to affirm the request.

- I am in a phase that was not properly annexed. Will I be accepted if I consent to join?

The properly annexed homeowners do not vote to let individual lots into the development, accepting some and rejecting others. They vote to accept "everyone in the excluded phases" who consents to come in. It's a blanket acceptance; you will not be singled out and turned down.

- What happens if the properly annexed owners do NOT vote to accept the unannexed phases?

From all indications, the current members are extremely anxious to welcome all of their fellow Glen Lake neighbors into the Association. They want the neighborhood to become what they thought it was, or was going to be, when they bought their homes. Nothing else makes sense, and nothing has changed since we each purchased our homes. After a few weeks, the Board members will contact those owners who have been too busy to complete and return a ballot and request that they do so as soon as possible. We will continue to contact owners in the phases annexed prior to 2012 until we have received the number of positive votes necessary to welcome the excluded phases.

- I have read on social media that 100% of those who need to be annexed need to consent before I can be admitted. Is that true?

No. Once 2/3rds of the owners of properly annexed lots vote in favor of accepting members from later phases, everyone who signed a consent form will be entered into the neighborhood HOA officially. The consent is individual and the membership is as well.

- I am in a phase that was not properly annexed. What happens if I don't sign the consent form?

It is not the first time that any developer has made an error like this. Given that most developers are involved in many neighborhoods at the same time, timelines slip through the cracks easily.

There is ample precedent available where the courts ruled in favor of homeowners associations. These verdicts are based on signed paperwork such as a PUD rider, plats, deeds, and behaviors such as using the amenities and common areas that the association offers.

- Why isn't the developer handling/paying for this?

Our legal counsel is in active discussion with the developer on this and other matters. Given the delicate nature of these negotiations, we cannot comment on this.

- What does the homeowners association (HOA) do?

The HOA owns and maintains the common areas which includes roads, curbs and sidewalks; the gates and surrounding areas; the club house, swimming pool and playgrounds; the lake and its surrounding areas; and several wetlands. By virtue of the governing documents, the HOA is also the point of contact with the County and utility companies for utility easements.

The business of the HOA is conducted by its Board of Directors and, on a day-to-day basis, the management company hired to perform administrative duties. One of the goals of the Board is to maintain and, when possible, improve property values within the neighborhood. The Board does this by overseeing the maintenance and administration of the common areas and amenities as well as by enforcing the common standards for the neighborhood as laid out in the governing documents (see, in particular, Articles VI, VII and VIII).

All of these maintenance and administrative costs are paid for from the annual assessments levied against owners. Every year, the Board develops a budget for the following fiscal year based on its best estimates of the funds necessary to both operate the Association during that year and make a meaningful contribution to Reserves. The annual assessment per owner is that cost estimate divided by the number of Association members.

- How many homes are affected?

There are 200 lots in the incorrectly annexed phases. There are 285 lots in the older, correctly annexed phases.

- I lost my Annexation Ballot. How can I get another?

Download the cover letter and explanatory attachments to make sure you are in the group of Lots that should complete a Ballot. If you are, download and print the Ballot (only one Ballot is to be submitted per Lot). Then:

* Vote on the Annexation issue and the Amendment by initialing in the appropriate spaces;
* Clearly print your name and address;
* Sign the Ballot;
* Return the Ballot to Hinson Management’s Office in person or via USPS Mail.

- I lost my Consent Form. How can I get another?

Download the cover letter to make sure you are in the group of Lots that should sign a Consent Form. If you are, you must request a new copy of your Consent Form because each Consent is written specifically for a particular Lot. Send email to legal@scglenlake.com including the full name(s) of the owner(s) of the Lot, your physical address, and the email address to which you want us to send the Form. We will send you a copy of your original Consent Form as a pdf file (if you cannot accept and print a pdf file, ask us to send your Consent Form by regular USPS mail). When you get it, make sure it describes your lot and lists all owners.

A paper version of the Consent Form must be signed in front of a Notary Public and two (2) witnesses. If more than one person is listed as an owner of the property, all owners’ signatures must be witnessed and notarized. So you should:

1. Print a copy of the Consent Form if you receive it in digital format, otherwise use the Form you receive by regular mail;
1. Locate a Notary and, if necessary, make an appointment;
1. Take any other co-owner(s) with you to the meeting with the Notary;
1. Clearly print the names of all owner(s) above the signature line(s) on the Consent Form;
1. Have all owners sign the Form, the Witnesses sign the Form, and the Notary sign and affix his or her seal;
1. Return the Consent Form to Hinson Management’s Office in person or via USPS Mail.

- Where can I find a Notary Public for my Consent Form?

Hinson Management will supply Notary service during regular business hours. The Spartanburg County Public Library system has notaries. Online searches and the ancient Yellow Pages are also good sources for notaries.

- Who can I contact if I have questions?

Questions of a general nature can be sent to legal@scglenlake.com. You will not receive a direct answer, but the question and answer might be included on this page.

Questions regarding your personal situation can be directed to John Crawford with Kennison, Dudley & Crawford at 864-242-4899

You can contact your personal legal counsel if desired.