# Noise

Sec. 30-28 - Unlawful noise.

> Except as provided in section 30-27, it shall be unlawful for any person to willfully make or cause to be made any unreasonably loud and unseemly noise which disturbs the peace and quiet in any unincorporated areas or which unreasonably causes discomfort and annoyance to any person in an unincorporated area of the county or is unreasonably disturbing to residents. This shall include, but not be limited to, noises made by motor vehicles, horns, mechanical devices, electrical devices, electronic devices, human voice, musical instruments, or all other unreasonably loud and disturbing noise which exceeds that which is reasonable under the circumstances.

From the sheriff's office:

> In general, the noise ordinance applies from 9:00PM through 7:00AM. An Officer needs to be dispatched so that they can assess the situation and give the person(s) a verbal warning, if needed. Once a warning has been given and the Officer is requested to respond back out to the same location (within the same time period), then it could result in a citation being written, at the Officers' discretion.   

So, unless the noise violation is beyond reasonable during the daytime, there is very little the police will do about it. Of course, the "reasonable" aspect of it can be subject to interpretation. A bike passing through the street once will probably be considered reasonable, your neighbor running the engine on a loud bike all day is no longer reasonable.