# Snow removal

1. What was the process for snow removal the last time it happened in January 2017?

In January 2017, Hinson sent a mailing to the neighborhood [about $1.00 per household] letting residents know that they must remove their cars from the street or that area wouldn’t be plowed.  Before the snow began, the road was pretreated.  Once the snow stopped, all streets that could be plowed were plowed.  An ice melt was scattered over all roads that were plowed.  Our vendor charged $3,000 for that single snow event.

1. If there is more than one company that does snow removal, when was the last time we compared prices? 

Hinson has never compared prices.  Typically snow removal is offered by a limited number of vendors.  It is a service that is needed infrequently and often requested at the last possible minute.  Under those circumstances, it is a seller's market.  Our Board hopes to include collecting bids during our budgeting process each year so we can establish relationships with our first and second choice vendors prior to the time we need them.

1. When it starts snowing on Friday night and we wake up to impassable roads Saturday morning will the snow removal people work on the weekend? 

Snow removal companies must have their equipment positioned at the client's location BEFORE the snow starts, so a decision has to be postponed as long as possible to take advantage of the latest predictions regarding the storm's track and intensity, but made far enough in advance that our preferred vendors are not already booked and can get into position before the storm.

1. Isn't this a lot like high stakes gambling using limited, imprecise information?  It seems there are a lot more ways to lose than to win.

Yes, that's a good analogy.  Interstate 85 is a weather corridor that often determines whether we get an inch or two of fluffy snow or a major sleet, snow, and ice event.  A storm that's predicted to bury us shifts north or south by a couple of miles and the ground is bare the next afternoon. A storm that's predicted to miss the Upstate drops south and we're buried.  If we secure a vendor and a big storm actually hits, everyone in the neighborhood is as happy as possible under the circumstances.  If we don't secure a vendor and the storm misses us, we're golden.  Any other combination leads to very unhappy residents.  Sadly, even the most well intentioned Board is likely to lose more often than win.

1. What will you do differently the next time a big snow is predicted?

If that happens this winter, we will gamble as wisely as possible and use the vendor Hinson hired in 2017.  We will send an email blast to all registered users of this site telling them to park their vehicles someplace else other than the street or gutter or sidewalk so all streets can be prepped, plowed, and topped off with ice melt.  We will likely also send an urgent post through Nextdoor.  Then, if you want your street plowed and your neighbors are parked on the street, assume they did not get the messages and go ask them pleasantly to move their car so the plow will come through.  If the rest of this winter is uneventful, we'll shop around for vendors and do the best we can next year at second-guessing the weather.