# Vehicles


## Golf carts

What are the rules on driving motorized vehicles like golf carts, ATV, mini-bikes, etc.?

Only licensed drivers 16 years of age or older. That means that it is illegal for young children or unlicensed drivers to drive a golf cart on a public road (which includes your neighborhood). It doesn’t matter if you’re seated next to your child; they still can’t drive. Also, if your child has an accident, you can be criminally liable for endangering your child and civilly liable for “negligent entrustment” for any accident caused by your child. Reference: https://www.charlestonlaw.net/golf-cart-laws-in-south-carolina/?fbclid=IwAR13G7n03Dz4lj4VqbZwk6O4rImg5k0BqanvE_xaOzL4p_xxqq2rsLxG1Yk

The Covenants state:
8.16 Vehicles and Parking. The term "vehicles," as used herein, shall include, without limitation, motor homes, boats, trailers, motorcycles, minibikes, scooters, go-carts, trucks, campers, buses, vans, and automobiles.
[...]
(f) No motorized vehicles shall be permitted on pathways or unpaved Common Area except for public safety vehicles and vehicles authorized by the Board.