# Appendix 1

Dear Fellow Glen Lake Homeowner:

The Nominations Committee is requesting nominations for three Board of Director positions for the Glenlake Upstate Homeowners Association.

If you or someone you know is interested and meets the Glenlake Bylaw criteria, please complete the attached nomination form.

Bylaw criteria:

1.  Elected directors must reside in the Glen Lake Subdivision
1.  Must be a member in good standing (or be a spouse of a member). A member is the legal owner of a lot in the Glen Lake Subdivision
1.  Cannot have a spouse concurrently on the Board.

All nominations must be delivered or mailed to Hinson Management at PO Box 160207, Boiling Springs no later than December 18, 2020. Nominations can also be submitted on [our website](https://www.scglenlake.com/p/Board-Election-Nominations-2021). After all nomination forms are received and candidates are confirmed by Nominations Committee, the candidates' biographies will be posted on the Glen Lake website.

Two Town Hall Meetings have been scheduled to allow all Glen Lake members to hear the candidates' answers to questions compiled by the Nominations Committee based on member suggestions. Questions may be submitted on [our website](https://www.scglenlake.com/p/Submit-questions-for-nominees) or via e-mail to [nominations\@scglenlake.com](mailto:nominations@scglenlake.com){.email}. Time permitting, questions from the floor may be possible.

Glen Lake members should make every effort to attend one of these meetings.

If you are a candidate, please plan to attend both Town Hall Meetings.

Nominee Town Hall Meetings will be held at the Glen Lake Clubhouse:

-   Saturday, January 16, 2021, 10:30am to 1:00pm
-   Thursday January 28, 2021, 6:30pm to 9:00pm

Cordially, The Nominations Committee