# Appendix 2. Example of announcement letter to the Annual Meeting

Dear Glen Lake homeowner:

The Annual Meeting of the Glenlake Homeowners Association, Inc is scheduled for Saturday, February 6, 2021 from 10:30 am to 1:00 pm at the Glen Lake Club House, 202 Stewarts Landing.  Please plan to arrive 10 to 15 minutes before the start of the meeting to register and receive your copy of the 2020 Financial Summary.

A ballot for election of the 2021 Board of Directors is enclosed.  If you have not met the candidates, please review the information posted on the [website](http://www.scglenlake.com) for background details.

For the election to be valid at least 25% of the homes in Glen Lake (i.e. 120) must return a ballot.  If you do not want to vote, please return your blank ballot so it can be counted toward the quorum.  If a quorum is not reached, the Annual Meeting will be postponed until a quorum can be reached.

All votes must be received at the offices of Hinson Management, Inc by 5:00 pm on Monday, February 1, 2021.  If a quorum has not been reached, the Annual Meeting will have to be postponed at significant cost to the community.

HOW TO RETURN YOUR BALLOT

1.	 After voting, fold the ballot and place in envelope marked “Ballot”.  Do NOT write anything on this envelope.  SEAL.
1.	 Place the ballot envelope inside the medium envelope with your return name and address in upper left corner. (correct any information, as needed).   SIGN and SEAL this envelope.  
1.	Place the 2-envelope ballot in the outer envelope addressed to Hinson Management, ATTN Glen Lake Board of Directors election.  SEAL. 

Mail or drop off at Hinson during business hours.

It is Hinson’s responsibility to use the unopened signed envelopes to verify your right to vote, record that your household has voted and add your vote to the quorum tally.  These envelopes are placed in the ballot box and, providing a quorum has been reached, will be publicly opened and counted at the Annual Meeting.

Sincerely,

The Board of Directors
