# Appendix 1b. Example nomination form

2019 Glenlake Upstate Homeowners Association Board Nomination

Name of person nominating:  										
Address of person nominating:  						

Information on Nominee
Name:  	   												
Address:     										
E-mail:  	   											

Pertinent work history: __________________________________________________________________ __________________________________________________________________________________________________________________________________________________________________________

Other skills, knowledge, & experience:  	___________________________________________________	
_____________________________________________________________________________________
_____________________________________________________________________________________

Reason(s) interested in serving:  								______
_____________________________________________________________________________________
_____________________________________________________________________________________

Most important factors facing the HOA:  ________________________						________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

If you are nominating someone else, has he/she agreed to serve?  ___ Yes; ___ No

The nominee acknowledges that serving on the Board is a significant time commitment (over 10 hours of meetings per month, and additionally 20 hours of activities per month). During budgeting and election time, this time commitment will be higher. The nominee acknowledges that the term for this Board position is two (2) years. The nominee agrees to sign the Board Member Code of Ethics when elected. ___ Yes;   ___  No

Would you be willing and able to serve as Officer on the board? ___ President; ___ Treasurer; ___ Secretary;
 ___ Vice-president
